<?php

namespace AppBundle\Repository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllChats($limit, $offset)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c.id AS id, c.topic, c.createdAt AS date')
            ->setMaxResults($limit);
        if ($offset) {
            $query->setFirstResult($offset);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @return mixed
     */
    public function dropAll()
    {
        return $this->_em->createQueryBuilder()
            ->delete('AppBundle:Chat', 'c')
            ->getQuery()
            ->execute();
    }

    /**
     * @param int $chatId
     * @return mixed
     */
    public function dropOne(int $chatId)
    {
        return $this->_em->createQueryBuilder()
            ->delete('AppBundle:Chat', 'c')
            ->where('c.id = :chatId')
            ->setParameters(
                [
                    'chatId'=> $chatId
                ]
            )->setMaxResults(1)
            ->getQuery()
            ->execute();
    }
}
