<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Chat;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Chat $chat
     * @param $limit
     * @param $offset
     * @return mixed
     */
    public function getAllMessages(Chat $chat, $limit, $offset)
    {
        $query = $this->createQueryBuilder('c')
            ->where('с.chat = :chatId')
            ->setParameters([
                'chatId' => $chat->getId(),
            ])
            ->setMaxResults($limit)
            ->getQuery();
        if ($offset) {
            $query->setFirstResult($offset);
        }
        return $query->getResult();
    }
}
