services:
    # Services
    user.service:
        class: AppBundle\Services\UserService
        public: true
        autowire: true
        arguments:
            $userManager: "@user.manager"
    # Managers
    user.manager:
        class: AppBundle\Manager\UserManager
        autowire: true
        public: true