AppBundle\Entity\Chat:
    type: entity
    table: chat
    repositoryClass: AppBundle\Repository\ChatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        topic:
            type: string
            length: 190
            options:
                unsigned: true
                fixed: false
        createdAt:
            type: datetime
            nullable: false
    oneToMany:
        message:
            targetEntity: AppBundle\Entity\Message
            cascade: [ 'persist', 'remove' ]
            fetch: EAGER
            mappedBy: chat
    options:
        collate: utf8mb4_general_ci
        charset: utf8mb4
    lifecycleCallbacks:
        prePersist:
            - setCreatedAtNow
        preUpdate:
            - setUpdatedAtNow