AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userToken:
            type: string
            unique: true
            length: 190
            options:
                unsigned: true
                fixed: false
        email:
            type: string
            length: 254
            unique: true
            options:
                fixed: false
        userName:
            type: string
            nullable: false
            length: 254
            options:
                fixed: false
        gender:
            type: enum
            values: ['male', 'female']
        createdAt:
            type: datetime
            nullable: false
    oneToMany:
        chat:
            targetEntity: AppBundle\Entity\Chat
            cascade: ["all"]
            fetch: EAGER
            mappedBy: user
        message:
            targetEntity: AppBundle\Entity\Message
            cascade: ["all"]
            fetch: EAGER
            mappedBy: user
    options:
        collate: utf8mb4_general_ci
        charset: utf8mb4
    lifecycleCallbacks:
        prePersist:
            - setCreatedAtNow
        preUpdate:
            - setUpdatedAtNow